[package]
name = "spinning_square"
version = "0.1.0"
authors = ["Titouan <titouanfreville@gmail.com>"]

[[bin]]
name = "spinning-square"

[dependencies]
piston = "0.53.1"
piston2d-graphics = "0.42.0"
pistoncore-glutin_window = "0.70.0"
piston2d-opengl_graphics = "0.81.0"
