[package]
name = "turtle_game"
version = "0.1.0"
authors = ["Titouan <titouanfreville@gmail.com>"]

[[bin]]
name = "turtles"

[dependencies]
piston = "0.31.1"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.35.0"
piston2d-opengl_graphics = "0.42.0"